import React, { useState, useEffect } from 'react';
import api from '../services/api';
import { useDispatch } from 'react-redux';
import { motion, AnimatePresence } from 'framer-motion';
import { addToast } from '../store/slices/uiSlice';
import {
  BookOpen, Sparkles, FileText, Printer, Loader2, Bookmark, Trash2, HelpCircle
} from 'lucide-react';
import GlassCard from '../components/ui/GlassCard';
import GradientButton from '../components/ui/GradientButton';
import MarkdownNotes from '../components/MarkdownNotes';

export default function Notes() {
  const dispatch = useDispatch();
  const [activeTab, setActiveTab] = useState('notes');
  const [subject, setSubject] = useState('');
  const [topic, setTopic] = useState('');
  const [notesContent, setNotesContent] = useState('');
  const [loading, setLoading] = useState(false);
  const [bookmarks, setBookmarks] = useState([]);
  const [loadingBookmarks, setLoadingBookmarks] = useState(false);
  const [expandedB, setExpandedB] = useState(null);

  const defaultNotes = [
    {
      title: "Bernoulli's Equation",
      subject: 'Fluid Mechanics',
      content: `### Bernoulli's Equation Overview\n\nFor incompressible, frictionless steady flow:\n\nP + ½ρv² + ρgh = Constant\n\nKey assumptions:\n• Non-viscous flow\n• Steady flow\n• Incompressible fluid\n• Along a single streamline`
    },
    {
      title: 'Constitution — Key Articles',
      subject: 'General Studies',
      content: `### Indian Constitution\n\n• Article 14 — Equality before law\n• Article 21 — Right to life\n• Article 32 — Constitutional remedies (heart & soul)\n• Article 44 — Uniform Civil Code\n• Article 324 — Election Commission`
    }
  ];

  const fetchBookmarks = async () => {
    setLoadingBookmarks(true);
    try {
      const res = await api.get('/auth/bookmarks');
      if (res.data.success) setBookmarks(res.data.data);
    } catch {
      dispatch(addToast({ message: 'Failed to load bookmarks', type: 'error' }));
    } finally { setLoadingBookmarks(false); }
  };

  useEffect(() => { if (activeTab === 'bookmarks') fetchBookmarks(); }, [activeTab]);

  const handleGenerateNotes = async (e) => {
    e.preventDefault();
    if (!subject || !topic) {
      dispatch(addToast({ message: 'Specify subject and topic', type: 'error' }));
      return;
    }
    setLoading(true);
    try {
      const res = await api.post('/ai/generate-notes', { subject, topic });
      if (res.data.success) {
        setNotesContent(res.data.data);
        dispatch(addToast({ message: 'Notes generated by AI', type: 'success' }));
      }
    } catch {
      dispatch(addToast({ message: 'Failed to generate AI notes', type: 'error' }));
    } finally { setLoading(false); }
  };

  const handleRemoveBookmark = async (id) => {
    try {
      const res = await api.delete(`/auth/bookmarks/${id}`);
      if (res.data.success) {
        setBookmarks((prev) => prev.filter((b) => b._id !== id));
        dispatch(addToast({ message: 'Removed', type: 'success' }));
      }
    } catch {
      dispatch(addToast({ message: 'Delete failed', type: 'error' }));
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
        <div>
          <h1 className="font-display text-3xl font-bold">
            Revision <span className="text-gradient">library</span>
          </h1>
          <p className="mt-2 text-sm text-slate-400">AI-generated formula sheets & bookmarked questions.</p>
        </div>
        <div className="flex rounded-xl border border-white/10 bg-white/[0.03] p-1">
          <TabButton active={activeTab === 'notes'} onClick={() => setActiveTab('notes')}>
            <Sparkles className="h-3.5 w-3.5" /> AI Notes
          </TabButton>
          <TabButton active={activeTab === 'bookmarks'} onClick={() => setActiveTab('bookmarks')}>
            <Bookmark className="h-3.5 w-3.5" /> Bookmarks
          </TabButton>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {activeTab === 'notes' ? (
          <motion.div
            key="notes"
            initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}
            className="grid grid-cols-1 gap-6 lg:grid-cols-3"
          >
            <div className="space-y-4">
              <GlassCard className="!p-6" hover={false}>
                <h3 className="mb-5 flex items-center gap-2 font-display text-base font-bold text-white">
                  <Sparkles className="h-4 w-4 text-neon-purple" />
                  Generate notes
                </h3>
                <form onSubmit={handleGenerateNotes} className="space-y-4">
                  <Input label="Subject" value={subject} onChange={setSubject} placeholder="e.g. Mechanical Engineering" />
                  <Input label="Topic" value={topic} onChange={setTopic} placeholder="e.g. Thermodynamics Laws" />
                  <GradientButton type="submit" disabled={loading} className="!w-full">
                    {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <><Sparkles className="h-4 w-4" /> Generate</>}
                  </GradientButton>
                </form>
              </GlassCard>

              <GlassCard className="!p-6" hover={false}>
                <h4 className="mb-4 text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400">Quick library</h4>
                <div className="space-y-2">
                  {defaultNotes.map((n, i) => (
                    <button
                      key={i}
                      onClick={() => setNotesContent(n.content)}
                      className="w-full rounded-xl border border-white/5 bg-white/[0.02] p-3 text-left transition hover:border-neon-blue/30 hover:bg-white/[0.05]"
                    >
                      <p className="text-[9px] font-bold uppercase tracking-[0.2em] text-neon-cyan">{n.subject}</p>
                      <p className="mt-1 text-sm font-semibold text-white">{n.title}</p>
                    </button>
                  ))}
                </div>
              </GlassCard>
            </div>

            <GlassCard className="!p-6 lg:col-span-2 min-h-[500px]" hover={false}>
              <div className="mb-5 flex items-center justify-between border-b border-white/5 pb-4">
                <h3 className="flex items-center gap-2 font-display text-base font-bold text-white">
                  <FileText className="h-4 w-4 text-neon-cyan" />
                  Notes viewer
                </h3>
                {notesContent && (
                  <button
                    onClick={() => window.print()}
                    className="rounded-lg border border-white/10 bg-white/[0.03] p-2 text-slate-400 hover:text-white"
                  >
                    <Printer className="h-4 w-4" />
                  </button>
                )}
              </div>
              {notesContent ? (
                <div className="notes-print max-w-none">
                  <MarkdownNotes source={notesContent} />
                </div>
              ) : (
                <div className="flex h-96 flex-col items-center justify-center gap-3 text-center text-slate-500">
                  <BookOpen className="h-12 w-12 text-slate-600" />
                  <p className="text-sm">Generate notes or pick a quick template to get started.</p>
                </div>
              )}
            </GlassCard>
          </motion.div>
        ) : (
          <motion.div
            key="bm"
            initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}
          >
            <GlassCard className="!p-6" hover={false}>
              <h3 className="mb-5 flex items-center gap-2 font-display text-base font-bold text-white">
                <Bookmark className="h-4 w-4 fill-amber-400 text-amber-400" />
                Bookmarked questions
              </h3>
              {loadingBookmarks ? (
                <div className="py-12 text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-neon-cyan" /></div>
              ) : bookmarks.length > 0 ? (
                <div className="space-y-3">
                  {bookmarks.map((b, idx) => {
                    const isExp = expandedB === b._id;
                    return (
                      <div key={b._id} className="rounded-xl border border-white/5 bg-white/[0.02] p-4 transition hover:border-white/10">
                        <div className="mb-2 flex items-center justify-between">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="rounded-full bg-neon-blue/10 px-2 py-0.5 text-[10px] font-bold uppercase tracking-[0.15em] text-neon-cyan ring-1 ring-neon-blue/20">
                              {b.examType || 'Tech'}
                            </span>
                            <span className="text-[10px] uppercase tracking-[0.15em] text-slate-500">{b.subject} · {b.topic}</span>
                          </div>
                          <button onClick={() => handleRemoveBookmark(b._id)} className="rounded-lg p-1.5 text-rose-400 hover:bg-rose-500/10">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                        <p
                          onClick={() => setExpandedB(isExp ? null : b._id)}
                          className="cursor-pointer text-sm font-semibold text-white hover:text-neon-cyan"
                        >
                          {idx + 1}. {b.question}
                        </p>
                        {isExp && (
                          <div className="mt-3 space-y-3 border-t border-white/5 pt-3">
                            <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
                              {b.options.map((opt, oi) => {
                                const isCorrect = b.correctAnswer === oi;
                                return (
                                  <div
                                    key={oi}
                                    className={`flex items-center gap-2 rounded-lg border p-2.5 text-xs ${
                                      isCorrect
                                        ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200'
                                        : 'border-white/5 bg-white/[0.02] text-slate-300'
                                    }`}
                                  >
                                    <span className={`flex h-6 w-6 items-center justify-center rounded-md font-mono text-[10px] font-bold ${
                                      isCorrect ? 'bg-emerald-500 text-white' : 'border border-white/10'
                                    }`}>
                                      {String.fromCharCode(65 + oi)}
                                    </span>
                                    {opt}
                                  </div>
                                );
                              })}
                            </div>
                            <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-xs">
                              <p className="mb-1 flex items-center gap-1.5 font-bold text-emerald-400">
                                <HelpCircle className="h-3.5 w-3.5" /> Solution
                              </p>
                              <p className="text-slate-300">{b.explanation}</p>
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="flex h-64 flex-col items-center justify-center gap-2 text-center text-slate-500">
                  <Bookmark className="h-10 w-10 text-slate-600" />
                  <p className="text-sm">No bookmarks yet.</p>
                  <p className="text-xs">Review scorecards and bookmark tough questions.</p>
                </div>
              )}
            </GlassCard>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function Input({ label, value, onChange, placeholder }) {
  return (
    <div className="space-y-2">
      <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400">{label}</label>
      <input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        required
        className="w-full rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2.5 text-sm text-white placeholder:text-slate-500 outline-none transition focus:border-neon-blue/60 focus:ring-2 focus:ring-neon-blue/15"
      />
    </div>
  );
}

function TabButton({ active, onClick, children }) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-bold transition ${
        active ? 'bg-gradient-blue-purple text-white shadow-neon-blue' : 'text-slate-400 hover:text-white'
      }`}
    >
      {children}
    </button>
  );
}
